name = "arena/l1-validator"
version = "0.0.0"
compiler = "v1.1.24"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'arena/l1-validator'"

[repository]
user = "arena"
project = "l1-validator"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v4.0.0"
source = "github"

[config]
